version: "3.7"

services:
  travelhoop:
      build:
        context: .
        dockerfile: ./docker/Dockerfile
        cache_from:
          - travelhoop:latest
      ports:
        - "3010:3010"
      env_file: 
        - ./src/app/travelhoop/.env.prod
      depends_on:
        - travelhoop-postgres
        - travelhoop-redis

  travelhoop-postgres:
      image: postgres:10-alpine
      container_name: travelhoop-postgres
      ports:
        - "5440:5432" 
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_USERNAME: postgres
        POSTGRES_DB: travelhoop
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 30s
        timeout: 30s
        retries: 3

  travelhoop-redis:
      image: redis:alpine
      ports:
        - "6379:6379"
        